### PR TITLE
Feature: add modified yolop tensorrt implementation

### PR DESCRIPTION
**Pull request by ausk**

### CODE REVIEW

**Comment by wang-xinyu** [comment]
@ausk 能否再检查一下，代码和readme有一些仍然写的是yolov5

**Comment by ausk** [comment]
@wang-xinyu fixed!

**Comment by wang-xinyu** [comment]
Thanks, merging it.

**Review by wang-xinyu — APPROVED** [review]

**Comment by wang-xinyu** [comment]
@ausk Readme中的操作步骤，是应该clone https://github.com/hustvl/YOLOP 还是你的fork版本https://github.com/ausk/YOLOP/ ？

**Comment by ausk** [comment]
@wang-xinyu  readme里那个主要是下载 pt 模型文件，可以下载官方的。不过官方后续可能会修改模型，也可能不会。

**Comment by wang-xinyu** [comment]
好的，所以yolop可以检测车辆，道路检测和道路分割，对吗？还有其他功能吗？

**Comment by HaiyangPeng** [comment]
Hi, @ausk :
I have a question about the following code:
https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolop/yolop.hpp#L217
The parameter of input is a pointer to the image data, but the data has not been copied to the CPU pinned memory. However, CUDA stream can only work on the pinned memory. So, I want to know whether there is a bug?

**Comment by HaiyangPeng** [comment]
Hi @wang-xinyu , if we do not set CPU pinned memory, the memory may be converted to other places e.g., disk. Will the data transferring between CPU and GPU be incorrect?

**Comment by wang-xinyu** [comment]
No, the CUDA API cudaMemcpyAsync will make sure the data transferring is correct.

**Pull request merged**
