### PR TITLE
Add: AlexNet, MobileNetV3, DenseNet121 Python Network Definition API

### PR DESCRIPTION
**Pull request by aditya-dl**

### CODE REVIEW

**Comment by wang-xinyu** [comment]
@aditya-dl Thanks for your interests.  Did you notice that the mobilenetv3 is not from torchvision? but your mobilenetv3.py is from torchvision, right?

**Comment by aditya-dl** [comment]
Yes, I didn't use the model from torchvision as there were certain differences with the layers. Thus, the mobilenetv3 model is from the repo given in the README.

**Comment by wang-xinyu** [comment]
OK, that's good. merging it.

But as the torchvision already includes mobilenetv3, I think it is better to use mobilenetv3 from torchvision. Do you have a plan to implement it for both c++ and python?

**Review by wang-xinyu — APPROVED** [review]

**Comment by aditya-dl** [comment]
Yes, I am planning to implement those in C++ and Python.

**Pull request merged**
