### PR TITLE
Arcface trt8

### PR DESCRIPTION
**Pull request by sbmalik**
added support for the latest ArcFace conversion & **TensorRT 8**

### CODE REVIEW

**Comment by wang-xinyu** [comment]
@sbmalik Thanks for the PR!

I have one doubt, with your changes, we still need to checkout to this old commit(3866cd77a6896c934b51ed39e9651b791d78bb57) of insightface repo to generate .wts file, right?

**Comment by sbmalik** [comment]
@wang-xinyu yes we have to checkout on that commit,

**Comment by wang-xinyu** [comment]
@sbmalik Got it.  
Have you tested any one of the **Previous Pre-trained models** after your changes?

**Comment by sbmalik** [comment]
@wang-xinyu I was unable to find the **Previous Pre-trained models** because insight-face have updated the structured a lot since then.

**Comment by wang-xinyu** [comment]
@sbmalik Yes, those models are missing in the Insightface model zoo.   They provided the .onnx models and weights for R50, etc.

Merging it, thanks a lot!

**Comment by sbmalik** [comment]
@wang-xinyu my pleasure

**Pull request merged**
