### PR TITLE
update rcnn

### PR DESCRIPTION
**Pull request by freedenS**
* fix bugs with R18 and R34
 add BasicBlock for R18 and R34
 add STRIDE_IN_1X1, MakeStage is same with detectron2 now.

* update README.md

### CODE REVIEW

**Review by wang-xinyu — COMMENTED** [review]
这个图片可以删掉然后提供一个下载链接吗？因为想保持repo size尽量小

**Comment by freedenS** [comment]
No problem! 😊

**Review by wang-xinyu — APPROVED** [review]

**Comment by freedenS** [comment]
@JiHooooo we just use cub library, maybe you can find it in cuda-11.1/include/cub
if not, you can also download from https://github.com/NVIDIA/cub

**Comment by Dorozhko-Anton** [comment]
@freedenS to build rcnn with CUDA 11 I had to modify the following files

```
 modified:   ../BatchedNms.cu
 modified:   ../PredictorDecode.cu
        modified:   ../RpnDecode.cu
        modified:   ../RpnNms.cu
```

1. I changed the includes 
```
//#include <thrust/system/cuda/detail/cub/device/device_radix_sort.cuh>
#include <cub/device/device_radix_sort.cuh>
```
2. Then I had to change  `thrust::cuda_cub::cub::` to `cub::`

**Comment by freedenS** [comment]
> @freedenS to build rcnn with CUDA 11 I had to modify the following files
> 
> ```
>  modified:   ../BatchedNms.cu
>  modified:   ../PredictorDecode.cu
>         modified:   ../RpnDecode.cu
>         modified:   ../RpnNms.cu
> ```
> 
> 1. change CMakeLists.txt
> 
> ```
> include_directories(/usr/local/cuda/include/cub)
> ```
> 
> 1. I changed the includes
> 
> ```
> //#include <thrust/system/cuda/detail/cub/device/device_radix_sort.cuh>
> #include <cub/device/device_radix_sort.cuh>
> ```
> 
> 1. Then I had to change  `thrust::cuda_cub::cub::` to `cub::`

yes, that's it!

**Pull request merged**
