### PR TITLE
the speed and resout of detr ?

### PR DESCRIPTION
**Pull request by henbucuoshanghai**
it has 59ms and 43ms for the samples.
and the resout :
_bus
_zidane

### CODE REVIEW

**Comment by henbucuoshanghai** [comment]
i change nothing of the original detr  in tensorrtx,
ubuntu GPU is 2060,trt is 7.2.2  .
They are right?  the speed and the resout image?

**Comment by freedenS** [comment]
you should set different INPUT_W, INPUT_H with different image, refer to the inference code in gen_wts.py for the correct result.
i think your latency with 2060 has no problem.

**Comment by freedenS** [comment]
We'd better talk about this in Issues.

**Comment by henbucuoshanghai** [comment]
detr需要45，60ms但是yolo5在我的机器上只需要3ms。请问对吗？

**Comment by wang-xinyu** [comment]
@henbucuoshanghai pls use ISSUE to discuss it, not PR. closing it.

**Pull request closed without merging**
