### PR TITLE
crnn: Fix compilation issues on Jetson

### PR DESCRIPTION
**Pull request by kirushyk**

### CODE REVIEW

**Comment by wang-xinyu** [comment]
any particular reason for make these changes?

**Comment by kirushyk** [comment]
Just to make it actually build-able:
* `CV_BGR2GRAY` was deprecated and is now removed from OpenCV interface. So now, when I try to compile CRNN, I see this error:
```
tensorrtx/crnn/crnn.cpp:376:28: error: ‘CV_BGR2GRAY’ was not declared in this scope
     cv::cvtColor(img, img, CV_BGR2GRAY);
                            ^~~~~~~~~~~
```
* `<fstream>` was not included, causing this:
```
tensorrtx/crnn/crnn.cpp:62:29: error: variable ‘std::ifstream input’ has initializer but incomplete type
tensorrtx/crnn/crnn.cpp:318:24: error: variable ‘std::ofstream p’ has initializer but incomplete type
```
* If `Logger::log` is not marked as `throw()`, it will produce error as well:
```
tensorrtx/crnn/logging.h:239:10: error: looser throw specifier for ‘virtual void Logger::log(nvinfer1::ILogger::Severity, const char*)’
     void log(Severity severity, const char* msg) override
          ^~~
In file included from /usr/include/aarch64-linux-gnu/NvInferLegacyDims.h:53:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:53,
                 from /home/ky/Developer/tensorrtx/crnn/crnn.cpp:5:
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:1222:18: error:   overriding ‘virtual void nvinfer1::ILogger::log(nvinfer1::ILogger::Severity, const AsciiChar*) noexcept’
     virtual void log(Severity severity, AsciiChar const* msg) noexcept = 0;
                  ^~~
```

**Comment by wang-xinyu** [comment]
@kirushyk what's the version of opencv and tensorrt on your device?

**Comment by kirushyk** [comment]
OpenCV 4.1.1
TensorRT 8.0.1.6-1 @ CUDA 10.2

**Comment by GalSang17** [comment]
> OpenCV 4.1.1 TensorRT 8.0.1.6-1 @ CUDA 10.2

your changes are right!!!, thank U

**Pull request closed without merging**
