### PR TITLE
added real-esrgan

### PR DESCRIPTION
**Pull request by yester31**
Please review my code

### CODE REVIEW

**Comment by wang-xinyu** [comment]
Hi @yester31 ,

Thanks for the PR!

Looks good to me.  Can we not upload bin image files to the repo? You can provide a download link for the image. Just want to keep the repo size small, because there are so many models in one repo.

Thanks.

**Comment by yester31** [comment]
The sample image was deleted from the repository and a download link was provided in the readme file.

**Comment by wang-xinyu** [comment]
@yester31 One more thing,   please use 4 space instead of tab. 

Thanks!

**Comment by yester31** [comment]
@wang-xinyu I changed all the tabs used in the code to 4 spaces.

**Review by wang-xinyu — APPROVED** [review]

**Comment by wang-xinyu** [comment]
@yester31 Thanks! merged.

**Comment by wang-xinyu** [comment]
@yester31 It will be great if you can share the demo image as well. The comparison of before and after processing. Just upload image in this thread, then add the link to the readme(I can also do this step).

**Comment by yester31** [comment]
@wang-xinyu I made the comparison image of before and after processing.
Please let me know if there are any mistakes.

https://drive.google.com/file/d/1UftRtmu7h8I0odapJLyaiEjSeQz3zl2-/view?usp=sharing
compare

**Comment by wang-xinyu** [comment]
@yester31 Can we have a similar one as https://github.com/xinntao/Real-ESRGAN/blob/master/assets/teaser.jpg? which is more obvious.
Just one of them would be fine.

**Comment by yester31** [comment]
@wang-xinyu  How about this?

compare

**Comment by wang-xinyu** [comment]
@yester31 This is cool, obvious.   Can we have left&right comparison?    The original image is too small.

**Comment by yester31** [comment]
@wang-xinyu How about this?

image

**Comment by wang-xinyu** [comment]
@yester31 Perfect, thanks,  I'm adding into the readme.

**Comment by yester31** [comment]
@wang-xinyu thanks

**Pull request merged**
