### PR TITLE
Dev obb

### PR DESCRIPTION
**Pull request by YiAnXS**
This is my first time committing a PR, thanks to open source, here are my changes:
Add a yolov8-obb model and adapt to the original code

### CODE REVIEW

**Comment by B1SH0PP** [comment]
哥们, 终于看到你的pr了

**Comment by lin-qing-ai** [comment]
你好 尝试你的 yolov8-obb 生成.engine文件 tensorrt识别的方式，遇到下面的问题想向你请教：
我的环境
jetson nano  ubuntu18.04
CUDA  10.2
TensorRT  8.2.1.8
PyTorch 1.10.0a0+git36449ea
cuDNN  8201
在这一步生成engine文件sudo ./yolov8_obb -s obb.wts best.engine n 有如下报错：
[08/19/2024-18:44:13] [E] [TRT] 3: (Unnamed Layer* 247) [Convolution]:kernel weights has count 64 but 960 was expected
[08/19/2024-18:44:13] [E] [TRT] 4: (Unnamed Layer* 247) [Convolution]: count of 64 weights in kernel, but kernel dimensions (1,1) with 64 input channels, 15 output channels and 1 groups were specified. Expected Weights count is 64 * 1*1 * 15 / 1 = 960
[08/19/2024-18:44:13] [E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 247) [Convolution]: number of kernel weights does not match tensor dimensions)
[08/19/2024-18:44:13] [E] [TRT] 4: [network.cpp::validate::2835] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.)
[08/19/2024-18:44:13] [E] [TRT] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
Build engine successfully!
yolov8_obb: /home/ubuntu/tensorrtx-master/yolov8/yolov8_obb.cpp:30: void serialize_engine(std::__cxx11::string&, std::__cxx11::string&, int&, std::__cxx11::string&, float&, float&, int&): Assertion `serialized_engine' failed.
zsh: abort      sudo ./yolov8_obb -s obb.wts best.engine n

但是每次换成sudo ./yolov8_det -s obb.wts best.engine n指令是可以正常生成engien文件，可以正常识别的但没有旋转检测效果。

是否是生成的.wts文件有误，因为使用的gen_wts.py 程序没有obb权重类型选择，自己只是自行修改了下，还是TensorRT 版本不兼容导致呢

**Comment by YiAnXS** [comment]
那一版固定了15个类别，需要在网络那里修改自定义类别数量。我修好好了但还没时间上传



---Original---
From: "Qing ***@***.***&gt;
Date: Tue, Aug 20, 2024 14:27 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [wang-xinyu/tensorrtx] Dev obb (PR #1539)




 
你好 尝试你的 yolov8-obb 生成.engine文件 tensorrt识别的方式，遇到下面的问题想向你请教：
 我的环境
 jetson nano  ubuntu18.04
 CUDA  10.2
 TensorRT  8.2.1.8
 PyTorch 1.10.0a0+git36449ea
 cuDNN  8201
 在这一步生成engine文件sudo ./yolov8_obb -s obb.wts best.engine n 有如下报错：
 [08/19/2024-18:44:13] [E] [TRT] 3: (Unnamed Layer* 247) [Convolution]:kernel weights has count 64 but 960 was expected
 [08/19/2024-18:44:13] [E] [TRT] 4: (Unnamed Layer* 247) [Convolution]: count of 64 weights in kernel, but kernel dimensions (1,1) with 64 input channels, 15 output channels and 1 groups were specified. Expected Weights count is 64 * 11 * 15 / 1 = 960
 [08/19/2024-18:44:13] [E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer 247) [Convolution]: number of kernel weights does not match tensor dimensions)
 [08/19/2024-18:44:13] [E] [TRT] 4: [network.cpp::validate::2835] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.)
 [08/19/2024-18:44:13] [E] [TRT] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
 Build engine successfully!
 yolov8_obb: /home/ubuntu/tensorrtx-master/yolov8/yolov8_obb.cpp:30: void serialize_engine(std::__cxx11::string&amp;, std::__cxx11::string&amp;, int&amp;, std::__cxx11::string&amp;, float&amp;, float&amp;, int&amp;): Assertion `serialized_engine' failed.
 zsh: abort      sudo ./yolov8_obb -s obb.wts best.engine n
 
但是每次换成sudo ./yolov8_det -s obb.wts best.engine n指令是可以正常生成engien文件，可以正常识别的但没有旋转检测效果。
 
是否是生成的.wts文件有误，因为使用的gen_wts.py 程序没有obb权重类型选择，自己只是自行修改了下，还是TensorRT 版本不兼容导致呢

**Comment by GalSang17** [comment]
> 那一版固定了15个类别，需要在网络那里修改自定义类别数量。我修好好了但还没时间上传
> […](#)
> ---Original--- From: "Qing ***@***.***&gt; Date: Tue, Aug 20, 2024 14:27 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [wang-xinyu/tensorrtx] Dev obb (PR #1539) 你好 尝试你的 yolov8-obb 生成.engine文件 tensorrt识别的方式，遇到下面的问题想向你请教： 我的环境 jetson nano ubuntu18.04 CUDA 10.2 TensorRT 8.2.1.8 PyTorch 1.10.0a0+git36449ea cuDNN 8201 在这一步生成engine文件sudo ./yolov8_obb -s obb.wts best.engine n 有如下报错： [08/19/2024-18:44:13] [E] [TRT] 3: (Unnamed Layer* 247) [Convolution]:kernel weights has count 64 but 960 was expected [08/19/2024-18:44:13] [E] [TRT] 4: (Unnamed Layer* 247) [Convolution]: count of 64 weights in kernel, but kernel dimensions (1,1) with 64 input channels, 15 output channels and 1 groups were specified. Expected Weights count is 64 * 11 * 15 / 1 = 960 [08/19/2024-18:44:13] [E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer 247) [Convolution]: number of kernel weights does not match tensor dimensions) [08/19/2024-18:44:13] [E] [TRT] 4: [network.cpp::validate::2835] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.) [08/19/2024-18:44:13] [E] [TRT] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. ) Build engine successfully! yolov8_obb: /home/ubuntu/tensorrtx-master/yolov8/yolov8_obb.cpp:30: void serialize_engine(std::__cxx11::string&amp;, std::__cxx11::string&amp;, int&amp;, std::__cxx11::string&amp;, float&amp;, float&amp;, int&amp;): Assertion `serialized_engine' failed. zsh: abort sudo ./yolov8_obb -s obb.wts best.engine n 但是每次换成sudo ./yolov8_det -s obb.wts best.engine n指令是可以正常生成engien文件，可以正常识别的但没有旋转检测效果。 是否是生成的.wts文件有误，因为使用的gen_wts.py 程序没有obb权重类型选择，自己只是自行修改了下，还是TensorRT 版本不兼容导致呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
你怎么删除了dev分支，什么时候重新上传呢？

**Pull request closed without merging**
