### PR TITLE
Change resize to letterbox to keep model pre-processing consistent

### PR DESCRIPTION
**Pull request by CharlesHuan**
Change resize to letterbox to keep model pre-processing consistent

### CODE REVIEW

**Comment by wang-xinyu** [comment]
Is it possible to reuse this preprocess function? https://github.com/wang-xinyu/tensorrtx/blob/3271725dd45d9597918bfccf4492e667bfda01b9/yolov5/src/calibrator.cpp#L11C16-L11C30

**Comment by CharlesHuan** [comment]
Thank you very much for your suggestion! the implementation is more concise!

**Comment by CharlesHuan** [comment]
> Is it possible to reuse this preprocess function?
> 
> https://github.com/wang-xinyu/tensorrtx/blob/3271725dd45d9597918bfccf4492e667bfda01b9/yolov5/src/calibrator.cpp#L11

Thank you very much for your suggestion! the implementation is more concise!

**Comment by wang-xinyu** [comment]
@CharlesHuan  Can we call preprocess_img() directly, instead of define a duplicated function.    Maybe remove that the `static tag`, and declare it in calibrator.h.    Or create a cpu_preprocess.cpp.

**Comment by CharlesHuan** [comment]
I'm sorry for my bad coding habits. T-T Is this a better implementation?

**Comment by wang-xinyu** [comment]
@CharlesHuan Great, thanks for your contribution!

**Pull request merged**
