### PR TITLE
modify load model for ema

### PR DESCRIPTION
**Pull request by AdanWang**
Yolov5 pt model may contain ema params, modify gen_wts.py to adapt it.

### CODE REVIEW

**Comment by wang-xinyu** [comment]
@AdanWang can you explain more on why do we need this?

**Comment by AdanWang** [comment]
我用U版v5的.pt文件生成的engine做推理发现比U版yolov5的推理结果总是少几个点，然后我查看了下，发现U版V5的模型参数和我通过gen_wts.py生成的参数不同。随后我查看了U版V5的模型加载部分，在experimental.py的98行与100行附近，如下图。我想到，之前yolov5在训练的时候，使用了EMA策略，即参数的指数移动平均。正常的更新参数存储在model['model']里面，而真正推理使用的参数在model['ema']中即指数加权平均后的结果，且指标会比model['model']的效果好很多。而gen_wts.py中直接加载的就是model['model']，因此导致了我在一开始的问题，通过修改gen_wts.py的模型加载方式，生成的engine模型指标，接近用U版val.py测试指标。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-xinyu/tensorrtx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-xinyu/tensorrtx] modify load model for ema (PR #929)





 
@AdanWang can you explain more on why do we need this?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wang-xinyu** [comment]
@AdanWang Cool, thanks
Does the model provided in release tag like https://github.com/ultralytics/yolov5/releases/tag/v6.1 also have ema?

**Comment by AdanWang** [comment]
> @AdanWang Cool, thanks Does the model provided in release tag like https://github.com/ultralytics/yolov5/releases/tag/v6.1 also have ema?

I have checked that the model provided in release tag like v6.1 does not have ema,  only the model trained with custom data.And  I also found that ema seems to be a default setting in yolov5, you can find it in line 186 at train.py.

**Comment by AdanWang** [comment]
> @AdanWang Cool, thanks Does the model provided in release tag like https://github.com/ultralytics/yolov5/releases/tag/v6.1 also have ema?

Actually I found that it was not a problem just for yolov5, you can also find it in timm, line 183 of validate.py and helpers.py.

**Comment by wang-xinyu** [comment]
@AdanWang Thanks for pointing out this.   

Is it possible to use his attempt_load() function directly? 
    https://github.com/ultralytics/yolov5/blob/caf7ad0500f8fc58567a7aa01ca91d5ee77691d6/models/experimental.py#L90

**Comment by AdanWang** [comment]
@wang-xinyu In my opinion, it may be unnecessary to use attempt_load(), most parts of this function are to create an ensemble model and do compatibility updates for pytorch. Only line 96 and line 100 are useful for us.

**Review by wang-xinyu — APPROVED** [review]

**Pull request merged**
