### PR TITLE
Updated gen_wts.py for yolov5 release 6.0

### PR DESCRIPTION
**Pull request by ajkdrag**

### CODE REVIEW

**Comment by bobo0810** [comment]
@ONNONS Can you print out model_keys？
`model_keys=model.state_dict().keys()`

**Comment by ONNONS** [comment]
I am a high school student

If you tell me how to do it, I will try and reply.

**Comment by ONNONS** [comment]
> @ONNONS Can you print out model_keys？ `model_keys=model.state_dict().keys()`

I am a high school student

If you tell me how to do it, I will try and reply.

**Comment by ONNONS** [comment]
@bobo0810 

I am a high school student

If you tell me how to do it, I will try and reply.

**Pull request closed without merging**
