### PR TITLE
add centernet dla34 ctdet task.

### PR DESCRIPTION
**Pull request by SsisyphusTao**
Add CenterNet detection model with backbone dla34,
official model ctdet_coco_dla_2x.pth has passed the exam.

### CODE REVIEW

**Review by wang-xinyu — COMMENTED** [review]
Cool, thanks, @SsisyphusTao ,  could you remove the .jpg files and provide a download link? Like the pics in https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/README.md.

**Comment by SsisyphusTao** [comment]
> Cool, thanks, @SsisyphusTao , could you remove the .jpg files and provide a download link? Like the pics in https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/README.md.

Sure, now I have removed the trt_out.jpg, but kept the original one for sample.

**Comment by wang-xinyu** [comment]
Thanks, can you also remove test.jpg and add a download link in readme like https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn#how-to-run?

**Comment by SsisyphusTao** [comment]
> Thanks, can you also remove test.jpg and add a download link in readme like https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn#how-to-run?
> Just want to keep repo size small.

OK，it's down.

**Review by wang-xinyu — APPROVED** [review]

**Comment by wang-xinyu** [comment]
Merged, thanks.

One more question, why did you rebuild tensorrt official plugins? Is it better to build an extra plugin.so and load it using python, just like yolov5 in this repo?

**Pull request merged**
