### PR TITLE
YOLOv3 TRT8 Fix

### PR DESCRIPTION
**Pull request by vjsrinivas**
Based off https://github.com/wang-xinyu/tensorrtx/pull/540
Successfully tested on Jetson NX Jetpack 4.6 w/ TensorRT 8.0.1.6. Used original YOLOv3 weights (previews attached below):

bus
zidane

### CODE REVIEW

**Comment by wang-xinyu** [comment]
@vjsrinivas why don't you put the #if -- #endif block in a common header? like what we did in yolov5.

**Comment by vjsrinivas** [comment]
@wang-xinyu I must have looked at an earlier commit of that yolov5 PR. I'll try to update it later this weekend.

**Comment by vjsrinivas** [comment]
I got really busy, apologies @wang-xinyu . I moved the ifelse to macros.h like yolov5. Tested on pretrained COCO weights, Jetson NX, and on TensorRT 8.0. Works as expected.

**Comment by wang-xinyu** [comment]
@vjsrinivas Looks good to me. Thanks for your contribution!

**Review by wang-xinyu — APPROVED** [review]

**Pull request merged**
